// L1: A global object with an owning member, destroyed during program exit.
// Guards allocation tracking for global variables (formerly gh-1): the report
// is generated by the runtime's own static destructor, so attribution depends
// on destruction ordering between the profiled global and the profiler state.
#include <cstddef>
#include <vector>

struct GlobalOwner {
    std::vector<std::byte> v;
    GlobalOwner() : v(3000) {}
    ~GlobalOwner() {}
};

GlobalOwner global_owner;

int main() { return 0; }
